[package]
authors = ["Derrick van Zyl <derrick.vanzyl@gmail.com>"]
edition = "2018"
name = "dragon"
version = "0.1.0"

[dependencies]
bootloader = "0.9.5"
spin = "0.5.2"
volatile = "0.2.6"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.4"
